In [1]:
import numpy as np
import pandas as pd
import os
from sentence_transformers import SentenceTransformer

/opt/conda/lib/python3.9/site-packages/torchvision/io/image.py:11: UserWarning: Failed to load image Python extension: /opt/conda/lib/python3.9/site-packages/torchvision/image.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev
  warn(f"Failed to load image Python extension: {e}")

#### Load data

In [2]:
# Main data directory
data_directory = './'
# Cleaned data
data_file_name = 'df_clean.csv'

# Load data into DataFrame
pd.set_option('display.max_columns', None)
df = pd.read_csv(os.path.join(data_directory, data_file_name), lineterminator='\n')
df.head()

,regio1,heatingType,telekomTvOffer,newlyConst,balcony,pricetrend,telekomUploadSpeed,totalRent,yearConstructed,hasKitchen,cellar,livingSpace,condition,streetPlain,lift,typeOfFlat,geo_plz,noRooms,floor,garden,regio2,description,facilities
0,Nordrhein_Westfalen,central_heating,ONE_YEAR_FREE,False,False,4.62,10.000000,840.00,1965.0,False,True,86.00,well_kept,Schüruferstraße,False,ground_floor,44269,4.0,1.000000,True,Dortmund,Die ebenerdig zu erreichende Erdgeschosswohnun...,Die Wohnung ist mit Laminat ausgelegt. Das Bad...
1,Sachsen,floor_heating,ONE_YEAR_FREE,True,True,2.72,2.400000,1300.00,2019.0,False,True,83.80,first_time_use,Turnerweg,True,apartment,1097,3.0,3.000000,False,Dresden,Der Neubau entsteht im Herzen der Dresdner Neu...,"* 9 m² Balkon\n* Bad mit bodengleicher Dusche,..."
2,Bremen,self_contained_central_heating,ONE_YEAR_FREE,False,True,2.46,28.920365,903.00,1950.0,False,False,84.97,refurbished,Hermann-Henrich-Meier-Allee,False,apartment,28213,3.0,1.000000,False,Bremen,Es handelt sich hier um ein saniertes Mehrfami...,Diese Wohnung wurde neu saniert und ist wie fo...
3,Bremen,central_heating,ONE_YEAR_FREE,False,True,1.89,2.400000,584.25,1959.0,False,True,60.30,well_kept,Lesumer_Heerstr.,False,ground_floor,28717,3.0,2.056523,False,Bremen,+ Komfortabler Bodenbelag: Die Wohnung ist zus...,Rollläden; Warmwasserbereiter; Kellerraum; Gas...
4,Baden_Württemberg,oil_heating,ONE_YEAR_FREE,False,False,3.77,40.000000,690.00,1970.0,True,True,53.00,well_kept,Hauptstraße,False,roof_storey,79211,2.0,2.000000,False,Emmendingen_Kreis,"Diese ansprechende, lichtdurchflutete DG-Wohnu...","Parkett, Einbauküche, kein Balkon"

In [3]:
df.describe(include="all")

,regio1,heatingType,telekomTvOffer,newlyConst,balcony,pricetrend,telekomUploadSpeed,totalRent,yearConstructed,hasKitchen,cellar,livingSpace,condition,streetPlain,lift,typeOfFlat,geo_plz,noRooms,floor,garden,regio2,description,facilities
count,173373,173373,173373,173373,173373,173373.000000,173373.000000,173373.000000,173373.000000,173373,173373,173373.000000,173373,173373,173373,173373,173373.000000,173373.000000,173373.000000,173373,173373,173373,173373
unique,16,13,3,2,2,NaN,NaN,NaN,NaN,2,2,NaN,10,41778,2,10,NaN,NaN,NaN,2,419,145394,153883
top,Nordrhein_Westfalen,central_heating,ONE_YEAR_FREE,False,True,NaN,NaN,NaN,NaN,False,True,NaN,well_kept,Hauptstraße,False,apartment,NaN,NaN,NaN,False,Leipzig,Das Objekt ist ein hochwertig saniertes und de...,Laminat
freq,41023,109060,167986,158299,110189,NaN,NaN,NaN,NaN,110458,116350,NaN,78130,40252,128836,107548,NaN,NaN,NaN,136617,9789,199,193
mean,NaN,NaN,NaN,NaN,NaN,3.478081,28.835647,845.354593,1967.663555,NaN,NaN,72.434032,NaN,NaN,NaN,NaN,37316.098660,2.605484,2.044556,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,1.921718,15.184535,577.176287,35.928589,NaN,NaN,27.020618,NaN,NaN,NaN,NaN,27881.483794,0.907195,1.317701,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,-2.000000,1.000000,1.000000,1856.000000,NaN,NaN,6.000000,NaN,NaN,NaN,NaN,1057.000000,1.000000,-1.000000,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,2.090000,10.000000,484.280000,1956.000000,NaN,NaN,54.500000,NaN,NaN,NaN,NaN,9127.000000,2.000000,1.000000,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,3.450000,40.000000,679.000000,1966.880541,NaN,NaN,68.000000,NaN,NaN,NaN,NaN,39106.000000,3.000000,2.000000,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,4.670000,40.000000,1030.000000,1994.000000,NaN,NaN,87.500000,NaN,NaN,NaN,NaN,57319.000000,3.000000,3.000000,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,8.560000,85.000000,19600.000000,2080.000000,NaN,NaN,134.000000,NaN,NaN,NaN,NaN,99994.000000,4.500000,6.000000,NaN,NaN,NaN,NaN

#### Create documents to be embedded

In [4]:
def create_docs(df):
    """
    Add 'passage: ' prefix to each document. 
    This is needed by the mixedbread-ai/deepset-mxbai-embed-de-large-v1 embedding model.
    """
    docs = df.tolist()
    docs = ["passage: " + desc for desc in docs]
    # Convert to numpy array
    docs = np.array(docs)
    return docs

In [6]:
description_docs = create_docs(df['description'])
# Print first 3 elements to verify
print("Description")
print(description_docs[:3])
print("Data array shape: ", description_docs.shape)
print("--------------------")

facilities_docs = create_docs(df['facilities'])
# Print first 3 elements to verify
print("Facilities")
print(facilities_docs[:3])
print("Data array shape: ", facilities_docs.shape)

Description
['passage: Die ebenerdig zu erreichende Erdgeschosswohnung befindet sich in einem gepflegten 8-Familienhaus. Aufgrund der Hanglage bietet sich ein unverbaubarer Blick ins Grüne.'
 'passage: Der Neubau entsteht im Herzen der Dresdner Neustadt.\nDas Baugrundstück befindet sich inmitten einer sehr gefragten Lage.\nNicht nur die zentrale Lage und die schnelle öffentliche\nVerkehrsanbindung durch den zu Fuß erreichbaren Bahnhof, wie auch Nahverkehrsanbindung, sondern auch die Architektur werden diesen\nNeubaukomplex zu einem weiteren Highlight am Dresdner Wohnungsmarkt machen.\nHier entstehen 2- bis 4-Raum Wohnungen mit Wohnflächen zwischen 43 m² und 124 m². Jede Wohnung verfügt über eine Terrasse oder einen Balkon, die Erdgeschosswohnungen erhalten zusätzlich einen Gartenanteil. Die Räumlichkeiten bieten großzügig durchdachte, lichtdurchflutete Räume mit effektiv geschnittenen Grundrissen.'
 'passage: Es handelt sich hier um ein saniertes Mehrfamilienhaus aus dem Jahr 1950. \n\r']
Data array shape:  (173373,)
--------------------
Facilities
['passage: Die Wohnung ist mit Laminat ausgelegt. Das Badezimmer ist gefliest und verfügt über eine Wannendusche. Neue weiße Zimmertüren, ein Fliesenspiegel in der Küche und Fußleisten wurden kürzlich eingebaut.\nZur Wohnung gehört ein 10 m großer Keller. Eine Garage kann optional mitgemietet werden.'
 'passage: * 9 m² Balkon\n* Bad mit bodengleicher Dusche, Badewanne und Fenster\n* Gäste-WC\n* Waschmaschinenanschluss im Bad und im Waschkeller\n* Abstell\n* Fußbodenheizung\n* Fliesen & Echtholzparkett\n* elektrische Rollläden\n* Videotürsprechanlage mit Farbdisplay\n* Aufzug\n* KfW-Effizienshaus 55\n* Tiefgaragenstellplatz (Miete bereits in der Gesamtmiete enthalten)\n\n~ Der Mietbeginn: ca. Anfang 2020\n~ Baustelle: Betreten verboten! Besichtigungen noch nicht möglich!'
 'passage: Diese Wohnung wurde neu saniert und ist wie folgt ausgestattet:\r\r- 3 geräumige Zimmer\r- Wohnzimmer mit optisch getrenntem Ess-,od. Arbeitsbereich\r- hochwertiger Vinylbodenbelag in allen Wohnräumen sowie im Flur\r- große Terrasse, hofseitig und mit Blick ins Grüne\r- Terrasse mit Markise , elektisch Bedienbar\r- neu und modern geflieste Küche mit Zugang zur Terrasse\r- kleine Speisekammer\r- neu und modern gefliestes Badezimmer mit Badewanne incl. Duschtrennwand\r\rJe nach Kapazität steht dem Mieter ein Keller zur Verfügung. \r\rEine Garage kann optional angemietet werden.\r']
Data array shape:  (173373,)

#### Load the embedding model and process documents

In [8]:
# Specify preferred dimensions, default is 1024
dimensions = 256

# Load model
embedding_model = SentenceTransformer("mixedbread-ai/deepset-mxbai-embed-de-large-v1", truncate_dim=dimensions)

In [9]:
# Encode texts

description_embeddings = embedding_model.encode(description_docs, show_progress_bar=True)
# Save the file for later use
np.save('embeddings/description_embeddings.npy', description_embeddings)

Batches:   0%|          | 0/5418 [00:00<?, ?it/s]

Processing Time: 10:06 on a H100

In [10]:
facilities_embeddings = embedding_model.encode(description_docs, show_progress_bar=True)
# Save the file for later use
np.save('embeddings/facilities_embeddings.npy', facilities_embeddings)

Batches:   0%|          | 0/5418 [00:00<?, ?it/s]

Processing Time: 11:15 on a H100